export const BUSINESS_LIST_REQUEST = "BUSINESS_LIST_REQUEST";
export const BUSINESS_LIST_SUCCESS = "BUSINESS_LIST_SUCCESS";
export const BUSINESS_LIST_FAIL = "BUSINESS_LIST_FAIL";

export const BUSINESS_DETAILS_REQUEST = "BUSINESS_DETAILS_REQUEST";
export const BUSINESS_DETAILS_SUCCESS = "BUSINESS_DETAIILS_SUCCESS";
export const BUSINESS_DETAILS_FAIL = "BUSINESS_DETAILS_FAIL";

export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST";
export const CREATE_REIVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";
export const CREATE_REVIEW_RESET = "CREATE_REVIEW_RESET";

export const USER_BUSINESS_REQUEST = "USER_BUSINESS_REQUEST";
export const USER_BUSINESS_SUCCESS = "USER_BUSINESS_SUCCESS";
export const USER_BUSINESS_FAIL = "USER_BUSINESS_FAIL";

export const CREATE_BUSINESS_REQUEST = "CREATE_BUSINESS_REQUEST";
export const CREATE_BUSINESS_SUCCESS = "CREATE_BUSINESS_SUCCESS";
export const CREATE_BUSINESS_FAIL = "CREATE_BUSINESS_FAIL";
export const CREATE_BUSINESS_RESET = "CREATE_BUSINESS_RESET";
